### ISSUE TITLE
model_catalogs doesn't import from full install

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/LibGOODS#17]
If I do:

`pip install model_catalogs`

then I can't import it:

```
$ python -c "import model_catalogs"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/chris.barker/miniconda3/envs/gnome_test/lib/python3.8/site-packages/model_catalogs/__init__.py", line 59, in <module>
    shutil.copy(
  File "/Users/chris.barker/miniconda3/envs/gnome_test/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/chris.barker/miniconda3/envs/gnome_test/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chris.barker/miniconda3/envs/gnome_test/lib/python3.8/site-packages/model_catalogs/catalogs/transform.yaml'
```

I think there's a data file not getting installed.

It works if you use an editable install.

**Comment by ChrisBarker-NOAA** [comment]
NOTE: I added the data files, but it won't actually work correctly.

The tests fail with:
`"complete" model source files are not yet available. Run `model_catalogs.complete_source_catalog()` to create this directory.`

But that won't work with a proper install -- it will only work with an editable install.

Not too horrible while under active development -- but I think we need to be a bit more clear about code vs data, and where generated files with be stored.

**Comment by lukecampbell** [comment]
@ChrisBarker-NOAA is this still an issue?

**Comment by ChrisBarker-NOAA** [comment]
Looks like this is working now -- closing.

**Comment by ChrisBarker-NOAA** [comment]
Reopening because I just noticed that the CI tests are using an editable install for the tests:

```
        run: |
          python -m pip install -e . --no-deps --force-reinstall
```

I think the tests should probably use a regular, non-editable install, to avoid similar issues arising in the future.
